---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
  html_document:
    df_print: paged
---

```{r, include=FALSE}
#reticulate::use_python("C:/Users/Liam/AppData/Local/Programs/Python/Python311/python.exe")
```

```{r}
setwd("E:/codes/r/tp12")
train_path <- "./images_train/"
validation_path <- "./images_validation/"
train_path2 <- "./images_train_2/"
```


```{r,  echo=TRUE}
library(keras)
set.seed(123)
```


```{r, eval=FALSE, echo=TRUE}
img_width <- 32
img_height <- 32

model.image <- keras_model_sequential() %>%
  #layer 1-2
  layer_conv_2d(filters = 64, kernel_size = c(3, 3), activation = "relu", padding = "same", 
                input_shape = c(img_width, img_height, 3)) %>%
  layer_conv_2d(filters = 64, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_max_pooling_2d(pool_size = c(2, 2), strides = c(2, 2)) %>%
  #layer 3-4
  layer_conv_2d(filters = 128, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_conv_2d(filters = 128, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_max_pooling_2d(pool_size = c(2, 2), strides = c(2, 2)) %>%
  #layer 5-7
  layer_conv_2d(filters = 256, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_conv_2d(filters = 256, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_conv_2d(filters = 256, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_conv_2d(filters = 256, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_max_pooling_2d(pool_size = c(2, 2), strides = c(2, 2)) %>%
  #layer 8-10
  layer_conv_2d(filters = 512, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_conv_2d(filters = 512, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_conv_2d(filters = 512, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_conv_2d(filters = 512, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_max_pooling_2d(pool_size = c(2, 2), strides = c(2, 2)) %>%
  #layer 11-13
  layer_conv_2d(filters = 512, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_conv_2d(filters = 512, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_conv_2d(filters = 512, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_conv_2d(filters = 512, kernel_size = c(3, 3), activation = "relu", padding = "same") %>%
  layer_max_pooling_2d(pool_size = c(2, 2), strides = c(2, 2)) %>%
  #flatten
  layer_flatten() %>%
  #layer 14
  layer_dense(units = 4096, activation = "relu") %>%
  layer_dropout(rate = 0.5) %>%
  #layer 15
  layer_dense(units = 4096, activation = "relu") %>%
  layer_dropout(rate = 0.5) %>%
  # layer 16, 3 classes
  layer_dense(units = 3, activation = "softmax")


opt <- optimizer_rmsprop(learning_rate = 1e-4,weight_decay = 1e-6)


model.image %>% compile(
  loss = "sparse_categorical_crossentropy",
  optimizer = opt,
  metrics = "accuracy"
)
summary(model.image)
```


```{r, eval=FALSE, echo=TRUE}
train_data <- image_dataset_from_directory(
  train_path,
  image_size = c(img_width, img_height),
  batch_size = 20,
)
validation_data <- image_dataset_from_directory(
  validation_path,
  image_size = c(img_width, img_height),
  batch_size = 20,
)
```
```{r, eval=FALSE, echo=TRUE}
history <- model.image %>% fit(
  train_data,
  epochs = 35,
  validation_data = validation_data,
  shuffle = TRUE,
  verbose = 2
)
```
```{r, eval=TRUE, echo=TRUE}
#plot(history)
#save("history",file="gogogo6_noval_32_image_vgg19_ep35_nogen.RData")
#save_model_tf(object=model.image, filepath="gogogo6_noval_32_image_vgg19_ep35_nogen_small")
loaded_model <- load_model_tf("32_image_resnet50_ep70_nogen.keras")
#loaded_model %>% save_model_tf("gogogo6_noval_32_image_vgg19_ep35_nogen_small.keras")
#model.image %>% save_model_tf("gogogo6_noval_32_image_vgg19_ep35_nogen.keras")
#model.image.load <- load_model_tf("32_image_vgg16_ep100.keras")
summary(loaded_model)
load("32_image_resnet50_ep70_nogen.RData")
plot(history)
```

