---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
  html_document:
    df_print: paged
---

```{r, include=FALSE}
#reticulate::use_python("C:/Users/Liam/AppData/Local/Programs/Python/Python311/python.exe")
```

```{r,eval=TRUE, echo=TRUE,cache=TRUE}
setwd("E:/codes/r/tp12")
train_path <- "./images_train/"
validation_path <- "./images_validation/"
```


```{r, eeval=TRUE, echo=TRUE,cache=TRUE}
library(keras)
#library(reticulate)
#library(tensorflow)
set.seed(123)
```



```{r, eval=TRUE, echo=TRUE,cache=TRUE}
img_width <- 32
img_height <- 32

image.model=application_resnet50(
  input_shape = c(32,32,3),
  weights = NULL,
  classes = 3,
  include_top = TRUE,
  classifier_activation="softmax",
  pooling = "max"
)
#help(application_resnet50)

#opt <- optimizer_adam(learning_rate = 1e-3)
opt <- optimizer_rmsprop(learning_rate = 1e-4, weight_decay = 1e-6)
image.model %>% compile(
  loss = "sparse_categorical_crossentropy",
  optimizer = opt,
  metrics = "accuracy"
)

###
summary(image.model)

```


```{r, eval=TRUE, echo=TRUE,cache=TRUE}
datagen <- image_data_generator(
  rescale = 1/255,
  #rotation_range=40,
  #width_shift_range=0.2,
  #height_shift_range=0.2,
  #shear_range = 0.2,
  #zoom_range = 0.2,
  horizontal_flip = TRUE,
  #fill_mode='nearest'
)
train_data <- image_dataset_from_directory(
  train_path,
  image_size = c(img_width, img_height),
  batch_size = 20,
)
validation_data <- image_dataset_from_directory(
  validation_path,
  image_size = c(img_width, img_height),
  batch_size = 20,
)

```
```{r, eval=TRUE, echo=TRUE,cache=TRUE}
history <- image.model %>% fit(
  train_data,
  epochs = 100,
  validation_data = validation_data,
  shuffle = TRUE,
  verbose = 2
)
```
```{r, eval=TRUE, echo=TRUE,cache=TRUE}
plot(history)
save("history",file="go4_32_image_resnet50_ep100_nogen.RData")
save_model_tf(object=image.model, filepath="go4_32_image_resnet50_ep100_nogen_small")
loaded_model <- load_model_tf("go4_32_image_resnet50_ep100_nogen_small")
loaded_model %>% save_model_tf("go4_32_image_resnet50_ep100_nogen_small.keras")
image.model %>% save_model_tf("go4_32_image_resnet50_ep100_nogen.keras")
#loaded_model <- load_model_tf("32_image_resnet50_ep200.keras")
```

